# Generated by Django 4.1.7 on 2023-03-13 12:44

import coach.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_training', models.SmallIntegerField(choices=[(0, 'Remote'), (1, 'Offline'), (3, 'Both')])),
                ('experience', models.SmallIntegerField(validators=[coach.models.experience_validator])),
                ('price', models.SmallIntegerField(validators=[coach.models.price_validator])),
                ('info_block', models.CharField(max_length=60)),
                ('additional_block', models.CharField(max_length=60)),
                ('category', models.SmallIntegerField(choices=[(0, 'Bodybuilding'), (1, 'Powerlifting'), (2, 'Armwrestling'), (3, 'Strongman'), (4, 'Armlifting'), (5, 'Gymnastic'), (6, 'Bikini Fitness')])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
