# Generated by Django 4.1.7 on 2023-03-27 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0002_alter_coach_options_userapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
