# Generated by Django 4.1.7 on 2023-03-27 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0003_alter_coach_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='coach.coach'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
