# Generated by Django 4.1.7 on 2023-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_alter_coach_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='city',
            field=models.CharField(default='blank', max_length=20),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='subject',
            field=models.CharField(default='blank', max_length=15),
        ),
    ]
