# Generated by Django 4.1.7 on 2023-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_coach_city_userapplication_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='subject',
            field=models.CharField(max_length=15),
        ),
    ]
