# Generated by Django 4.1.7 on 2023-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_alter_coach_city_alter_userapplication_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='additional_block',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='coach',
            name='info_block',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
