# Generated by Django 4.1.7 on 2023-02-27 10:41

from django.db import migrations
import django_resized.forms
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=False, quality=-1, scale=None, size=[512, 512], upload_to=user.models.avatar_path),
        ),
    ]
