# Generated by Django 4.1.7 on 2023-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Coach')]),
        ),
    ]
