# Generated by Django 4.1.7 on 2023-03-05 20:46

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='verifying',
            field=models.OneToOneField(default=user.models.UserVerification.get_new, on_delete=django.db.models.deletion.CASCADE, to='user.userverification'),
        ),
    ]
