# Generated by Django 4.1.7 on 2023-03-13 09:09

import coach.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_training', models.IntegerField(choices=[(0, 'Дистанійно'), (1, 'На місці')])),
                ('experience', models.IntegerField(validators=[coach.models.experience_validator])),
                ('price', models.IntegerField(validators=[coach.models.price_validator])),
                ('info_block', models.CharField(max_length=60)),
                ('additional_block', models.CharField(max_length=60)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
