# Generated by Django 4.1.7 on 2023-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Coach')], editable=False),
        ),
    ]
