# Generated by Django 4.1.7 on 2023-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
    ]
