# Generated by Django 4.1.7 on 2023-04-18 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
