# Generated by Django 4.1.7 on 2023-04-28 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_myuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0.0)]),
        ),
    ]
